name: CD_publish

on:
  push:

#on:
#  push:
#    branches:
#      - '[0-9]+.[0-9]+.[0-9]+'
#      - '[0-9]+.[0-9]+.[0-9]+-*'
#
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install EMMOntoPy and pyvode
        run: |
          pip install --upgrade pip
          pip install pylode==2.13.2 git+https://github.com/EMMO-REPO/EMMOntoPy.git

      - name: Create build directory
        run: mkdir build

      - name: Copy json-ld context
        run: cp -r context build/.

      #- name: Generate squashed ontology
      #  run: ontoconvert -saw
      #    -c 'http://www.w3.org/2004/02/skos/core#prefLabel-->http://www.w3.org/2000/01/rdf-schema#label'
      #    -c 'elucidation-->http://www.w3.org/2000/01/rdf-schema#comment'
      #    -c 'definition-->http://www.w3.org/2000/01/rdf-schema#comment'
      #    oteio.ttl build/oteio.ttl
      #    #-c 'comment-->http://www.w3.org/2000/01/rdf-schema#comment'

      #- name: Generate inferred ontology
      #  run: ontoconvert -saw --reasoner=HermiT
      #    -c 'http://www.w3.org/2004/02/skos/core#prefLabel-->http://www.w3.org/2000/01/rdf-schema#label'
      #    -c 'elucidation-->http://www.w3.org/2000/01/rdf-schema#comment'
      #    -c 'definition-->http://www.w3.org/2000/01/rdf-schema#comment'
      #    oteio.ttl build/oteio-inferred.ttl
      #    #-c 'comment-->http://www.w3.org/2000/01/rdf-schema#comment'

      - name: Generate documentation
        #run: pylode -i build/oteio-inferred.ttl -o build/oteio.html -p ontdoc
        run: |
          pylode -i pipeline.ttl -o build/oteio.html -p ontdoc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build  # The folder the action should deploy.
